### ISSUE TITLE
Performances in two tables in README are different?

### ISSUE THREAD

**Issue by laisimiao** [OpenSpaceAI/UVLTrack#6]
Table1:
![911f258a-c9e6-4a9c-82f5-0486a3ffb9a2](https://github.com/OpenSpaceAI/UVLTrack/assets/37405764/852c3a9d-0526-4042-8cab-2b84df6f3f1f)
Table2:
![2773765d-70a2-44dd-bd48-39c0cd5eff97](https://github.com/OpenSpaceAI/UVLTrack/assets/37405764/60666e78-76de-4858-9251-e2c19837ccf7)

And in table2, `NL+BBOX` performance is lower than `BBOX`, what's the discovery?

**Comment by 568xiaoma** [comment]
Table 1 shows the performance reported in the paper. Table 2 shows the performance of the released checkpoint.

We use mixed modal data (NL, BBOX, NL+BBOX) to train the model. Empirically, the more NL+BBOX samples, the better NL+BBOX tracking performance. Thus, NL+BBOX reference does not absolutely perform better than BBOX reference for our tracker. In our paper, we adopt a relatively balanced sample proportion to achieve good performance across different modal references.

**Comment by laisimiao** [comment]
So no checkpoint  corresponding to performance in the paper release? 
I think the community prefers the consistent checkpoint to plot figures in their future research.

**Comment by 568xiaoma** [comment]
Thank you for your attention and advice. The raw results are consistent with the paper, which provides the reference of our tracker for their future research. But, the original checkpoints were broken during migration, so we retrain our model and release the last checkpoint.

**Comment by laisimiao** [comment]
No wonder. Thank you and your nice work.
