### ISSUE TITLE
Your TNL2k raw results is inflated?

### ISSUE THREAD

**Issue by laisimiao** [OpenSpaceAI/UVLTrack#7]
It seems you use python analysis_results to evaluate tnl2k, which is higher than the official matlab toolkit.
This is a common and wrong way to get the SUC on tnl2k in sot community.

**Comment by 568xiaoma** [comment]
The evaluation and comparison of tnl2k performance are consistent with [JointNLT (CVPR2023)](https://github.com/lizhou-cs/JointNLT), which is our main baseline for vision-language tracking.
