### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by NakrAi** [OpenSpaceAI/UVLTrack#8]
有没有人碰到这个问题啊Model name 'pretrain/bert/bert-base-uncased-vocab.txt' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'pretrain/bert/bert-base-uncased-vocab.txt' was a path or url but couldn't find any file associated to this path or url.

**Comment by NakrAi** [comment]
![U@C4)~0(}PPQILUO3 U%OPS](https://github.com/OpenSpaceAI/UVLTrack/assets/152459373/9037be87-a32a-469f-aed6-cc3780a7389b)
他这个有点奇怪，第一次 p_total=5.2,第二次 p_total=4，第三次 p_total=0,这是为啥啊，看到求回复啊，谢谢啦

**Comment by 568xiaoma** [comment]
第一个问题是没有把相关文件放到```<PROJECT_ROOT>/pretrain```目录内，导致其检索了默认模型，请将下载后的[BERT](https://drive.google.com/drive/folders/1UZTrGcL3YlxvNpHi0wKsO_sKsTYuYnFo?usp=sharing)放在```<PROJECT_ROOT>/pretrain```。
第二个问题这里用到的p_dataset在配置文件中```cfg.DATA.TRAIN.DATASETS_RATIO``````cfg.DATA.VALTRACK.DATASETS_RATIO``````cfg.DATA.VALVL.DATASETS_RATIO```设置，三次p_total不同是因为训练时分别加载了这三种数据集，出现0时请检查是否正确设置了这些DATASETS_RATIO，另外如果不需要在训练中使用验证集，可以在```lib/train/base_function.py```151行到191行注释掉。
