### ISSUE TITLE
关于训练细节

### ISSUE THREAD

**Issue by Midkey** [OpenSpaceAI/UVLTrack#9]
您的工作十分优秀！我这里有一些问题想请教一下。
我们尝试复现您的方法，在训练后发现精度与论文所述相距较远。
github中提及Base模型在LaSOT BBOX, TNL2K NLBBOX 和 TNL2K NL的AUC精度分别为 69.5, 62.9和55.0
我复现的的结果为 68.8, 63.1和53.8
在训练过程参数与github中代码一致，Pytorch使用的1.9，使用8卡V100进行训练。
从结果上看，LaSOT BBOX和TNL2K NL的精度具有差距。
因此想请教一下，是否有些细节参数会影响精度以及您使用的训练设备。
scripts/train.sh里面默认是2卡训练，是否使用更多卡训练需要调整学习率等参数。
如果您能提供log文件，将有更大帮助~ 十分感谢~

**Comment by 568xiaoma** [comment]
感谢对我们工作的关注，以下是一些调试的建议，希望对你有所帮助：
1. 使用更多的GPU意味着更大的batchsize，尝试与batchsize成比例地提升学习率。根据你的描述，可以将学习率提升四倍。
2. 建议将pytorch切换到1.10.1从而与初始实现保持一致。
3. 训练log已经上传在[百度网盘](https://pan.baidu.com/s/1xSRgHHZKv8MyqMKwtT_JsA?pwd=8v0p)。

**Comment by ppt900** [comment]
您好，在使用代码进行训练，初始化refcocog时，        self.im_dir, self.covert_bbox, self.img_names, self.phrases = self.get_split_info('gref')函数中使用了/ssd/myc/VL_project/VLTVG/split/data/gref/gref_train.pth文件，可是并没有在您提供的代码中找到。请问，问题该如何解决呢？
